### ISSUE TITLE
How to dynamically add elements?

### ISSUE THREAD

**Issue by analytik** [elbywan/hyperactiv#12]
Hi. Thank you for this wonderful library! I'm trying to use it with Vue and I'm wondering what is the recommended approach to adding observed elements dynamically.

My original idea was to just have 1 store and dynamically add all the site features to it, but I feel like there's going to be caveats I don't see yet. Do you have any "official" approach?

Also, the `bubble` option isn't documented - is it relevant?

**Comment by elbywan** [comment]
Hi @analytik, sorry for the late reply…

> Hi. Thank you for this wonderful library!

…and thanks a bunch 👍.

>  I'm trying to use it with Vue and I'm wondering what is the recommended approach to adding observed elements dynamically.

Unfortunately it's been ages since I've used Vue.js for the last time, so it will be hard for me to help on this :/.

I would advise trying the same logic as the [react addon](https://github.com/elbywan/hyperactiv/tree/master/src/react):

1- Find a way to calculate which store dependencies are need to render a component template. Might be by creating a higher-order component and use a [render function](https://vuejs.org/v2/guide/render-function.html) (not a template) that is wrapped inside a `computed(() => { /* ... */})` call.

2 - Use the `callback` property to [$forceUpdate()](https://vuejs.org/v2/api/#vm-forceUpdate) the component when on of the dependencies changed. (See [here](https://github.com/elbywan/hyperactiv/blob/master/src/react/watchHoc.js#L31) for the react version)

3 - Dispose the callback function reference ($forceUpdate) when the component gets unmounted to prevent stale updates.

> My original idea was to just have 1 store and dynamically add all the site features to it, but I feel like there's going to be caveats I don't see yet. Do you have any "official" approach?
Unfortunately it's been ages since I used Vue.js for the last time. 

There is no official approach really - having one or multiple stores should work the same way and it depends on your needs and programming style.

> Also, the bubble option isn't documented - is it relevant?

It is related to `handlers` and documented [here](https://github.com/elbywan/hyperactiv/tree/master/src/handlers#usage). I guess it's not relevant, no.

**Comment by analytik** [comment]
Ah man, thanks so much! No worries about the delay, you don't owe me anything after all :)

That's all good advice, and exactly the kind of thing I wouldn't figure on my own any time soon. Having a render function inside computed() is brilliant.

Just in case anyone else stumbles on this, the tl;dr of how Vue+hyperactiv behave is

- hyperactiv works well with dynamically added properties, obviously, if they're used inside its `computed()` (caveat: read further)
- and Vue works well out of the box with properties that exist by the time the Vue component is created, and no extra hyperactiv logic is needed besides using them all in the `hyperactiv.computed()` function (not Vue computed())
- dynamically added properties work well IF you go through all of them in some `Object.keys()` loop inside `hyperactiv.computed()` AND then you change some other hyperactiv store property that's rendered at least once
  - the reason is that the function inside computed() needs to run at least once, but it doesn't know it needs to run on the new nested property until you run it by changing something else
- if some hyperactiv store elements displayed by a Vue component are used inside `hyperactiv.computed()` and some not, the ones used are updated immediate in templates, and the others are updated when the template is updated by something else (potentially never)
- one bug that I haven't solved or understood the cause of yet is when I use both Vue `computed()` and `hyperactiv.computed()` on one element. 
  - Let's say you observe something like `hyperstore.something = {a: 2, b: 4}` 
  - and also `hyperactiv.computed()` both of them then. 
  - Then, in a Vue template have `{{ hyperstore.something.foo || 'empty' }}` - this `foo` displays correctly once you update `a` or `b`, as explained above. 
  - But when you also have Vue computed property `foo2() { return hyperstore.something.foo || 'whatever' }` then `{{ foo2 }}` in the template never work. 
  - (This is not an issue, just a quirk that I can't explain yet.)
