### ISSUE TITLE
Doesn't work when deleting properties

### ISSUE THREAD

**Issue by W4G1** [elbywan/hyperactiv#15]
```javascript
const { observe } = require('hyperactiv')
const { write } = require('hyperactiv/handlers')

let copy = {}
let obj = observe({
    __handler: write(copy)
})

obj.a = 10

console.log(copy.a) // 10

delete obj.a

console.log(copy.a) // 10 (should be undefined)
```

When you delete a property of `obj`, the `__handler` method is not called and therefore `copy` is not updated.

Any ideas how to fix this?

**Comment by elbywan** [comment]
Hi @W4G1,

Yes this is an unfortunate limitation when using handlers, since the base library only observes property mutation events (set/get).

As a workaround, you could either set the property to `undefined` instead of deleting it or write a Proxy that will mimic the property deletion on the copy object.

```js
// Either:

obj.a = undefined

// Or:

obj = new Proxy(obj, {
    deleteProperty(target, prop) {
        delete target[prop]
        delete copy[prop]
    }
})
delete.obj.a
```

**Comment by W4G1** [comment]
That's unfortunate indeed, but understandable.

I'm currently using a mix of both workarounds you mentioned.

I use a Proxy trap — `deleteProperty()` — to catch the property deletion where I first set the property to `undefined` which triggers the `__handler` method. Then I actually `delete` it from both objects.
